name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: set up JDK 16
      uses: actions/setup-java@v6
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: gradle
        name: artifact
          path: adbTool/build/compose/binaries/main-release

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageReleaseMsi
